In [1]:
# Dependencies
import pandas as pd
import csv

In [2]:
#importing datasets
recovered = pd.read_csv('Resources/time_series_19-covid-Recovered.csv')
deaths = pd.read_csv('Resources/time_series_19-covid-Deaths.csv')
confirmed = pd.read_csv('Resources/time_series_19-covid-Confirmed.csv')

In [3]:
recovered.head()

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,2/23/20,2/24/20,2/25/20,2/26/20,2/27/20,2/28/20,2/29/20,3/1/20,3/2/20,3/3/20
0,Anhui,Mainland China,31.8257,117.2264,0,0,0,0,0,0,...,637,663,712,744,792,821,868,873,917,936
1,Beijing,Mainland China,40.1824,116.4142,0,0,1,2,2,2,...,189,198,215,235,248,257,271,276,282,288
2,Chongqing,Mainland China,30.0572,107.8740,0,0,0,0,0,0,...,335,349,372,384,401,422,438,450,469,490
3,Fujian,Mainland China,26.0789,117.9874,0,0,0,0,0,0,...,170,183,199,218,228,235,243,247,255,260
4,Gansu,Mainland China,36.0611,103.8343,0,0,0,0,0,0,...,78,80,80,81,81,82,82,84,85,86

In [15]:
# recovered.groupby(["Country/Region","Province/State"]).sum().drop(columns=["Lat","Long"]).transpose()
recovered.pivot(columns=['1/22/20','1/23/20'],values='Country/Region')

KeyError: 'Level 1/22/20 not found'

In [4]:
deaths.head()

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,2/23/20,2/24/20,2/25/20,2/26/20,2/27/20,2/28/20,2/29/20,3/1/20,3/2/20,3/3/20
0,Anhui,Mainland China,31.8257,117.2264,0,0,0,0,0,0,...,6,6,6,6,6,6,6,6,6,6
1,Beijing,Mainland China,40.1824,116.4142,0,0,0,0,0,1,...,4,4,4,4,5,7,8,8,8,8
2,Chongqing,Mainland China,30.0572,107.8740,0,0,0,0,0,0,...,6,6,6,6,6,6,6,6,6,6
3,Fujian,Mainland China,26.0789,117.9874,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
4,Gansu,Mainland China,36.0611,103.8343,0,0,0,0,0,0,...,2,2,2,2,2,2,2,2,2,2

In [5]:
confirmed.head()

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,2/23/20,2/24/20,2/25/20,2/26/20,2/27/20,2/28/20,2/29/20,3/1/20,3/2/20,3/3/20
0,Anhui,Mainland China,31.8257,117.2264,1,9,15,39,60,70,...,989,989,989,989,989,990,990,990,990,990
1,Beijing,Mainland China,40.1824,116.4142,14,22,36,41,68,80,...,399,399,400,400,410,410,411,413,414,414
2,Chongqing,Mainland China,30.0572,107.8740,6,9,27,57,75,110,...,575,576,576,576,576,576,576,576,576,576
3,Fujian,Mainland China,26.0789,117.9874,1,5,10,18,35,59,...,293,293,294,294,296,296,296,296,296,296
4,Gansu,Mainland China,36.0611,103.8343,0,2,2,4,7,14,...,91,91,91,91,91,91,91,91,91,91