In [2]:
# Dependencies
import pandas as pd
import csv
from sqlalchemy import create_engine
import plotly.express as px

In [3]:
#importing datasets
recovered = pd.read_csv('Resources/time_series_19-covid-Recovered.csv')
deaths = pd.read_csv('Resources/time_series_19-covid-Deaths.csv')
confirmed = pd.read_csv('Resources/time_series_19-covid-Confirmed.csv')

In [4]:
recovered.head()
recovered = recovered.drop(columns=['Lat', 'Long'])
df_recovered = pd.melt(recovered, id_vars=["Province/State", "Country/Region"])
df_recovered = df_recovered.rename(columns={"value": "Recovered Count", "variable": "Date"})
df_recovered.head()

  Province/State  Country/Region     Date  Recovered Count
0          Anhui  Mainland China  1/22/20                0
1        Beijing  Mainland China  1/22/20                0
2      Chongqing  Mainland China  1/22/20                0
3         Fujian  Mainland China  1/22/20                0
4          Gansu  Mainland China  1/22/20                0

In [5]:
deaths.head()
deaths = deaths.drop(columns=['Lat', 'Long'])
df_deaths = pd.melt(deaths, id_vars=["Province/State", "Country/Region"])
df_deaths = df_deaths.rename(columns={"value": "Deaths Count", "variable": "Date"})
df_deaths.head()

  Province/State  Country/Region     Date  Deaths Count
0          Anhui  Mainland China  1/22/20             0
1        Beijing  Mainland China  1/22/20             0
2      Chongqing  Mainland China  1/22/20             0
3         Fujian  Mainland China  1/22/20             0
4          Gansu  Mainland China  1/22/20             0

In [6]:
confirmed.head()
confirmed = confirmed.drop(columns=['Lat', 'Long'])
df_confirmed = pd.melt(confirmed, id_vars=["Province/State", "Country/Region"])
df_confirmed = df_confirmed.rename(columns={"value": "Confirmed Count", "variable": "Date"})
df_confirmed.head()

  Province/State  Country/Region     Date  Confirmed Count
0          Anhui  Mainland China  1/22/20                1
1        Beijing  Mainland China  1/22/20               14
2      Chongqing  Mainland China  1/22/20                6
3         Fujian  Mainland China  1/22/20                1
4          Gansu  Mainland China  1/22/20                0

In [7]:
df_combined = df_recovered.merge(df_deaths, on=("Province/State", "Country/Region", "Date"))
df_combined

,Province/State,Country/Region,Date,Recovered Count,Deaths Count
0,Anhui,Mainland China,1/22/20,0,0
1,Beijing,Mainland China,1/22/20,0,0
2,Chongqing,Mainland China,1/22/20,0,0
3,Fujian,Mainland China,1/22/20,0,0
4,Gansu,Mainland China,1/22/20,0,0
...,...,...,...,...,...
6337,"Berkeley, CA",US,3/3/20,0,0
6338,"Maricopa County, AZ",US,3/3/20,0,0
6339,"Wake County, NC",US,3/3/20,0,0
6340,"Westchester County, NY",US,3/3/20,0,0
6341,NaN,Ukraine,3/3/20,0,0

In [8]:
df_combined = df_combined.merge(df_confirmed, on=("Province/State", "Country/Region", "Date"))
df_combined

,Province/State,Country/Region,Date,Recovered Count,Deaths Count,Confirmed Count
0,Anhui,Mainland China,1/22/20,0,0,1
1,Beijing,Mainland China,1/22/20,0,0,14
2,Chongqing,Mainland China,1/22/20,0,0,6
3,Fujian,Mainland China,1/22/20,0,0,1
4,Gansu,Mainland China,1/22/20,0,0,0
...,...,...,...,...,...,...
6337,"Berkeley, CA",US,3/3/20,0,0,1
6338,"Maricopa County, AZ",US,3/3/20,0,0,1
6339,"Wake County, NC",US,3/3/20,0,0,1
6340,"Westchester County, NY",US,3/3/20,0,0,1
6341,NaN,Ukraine,3/3/20,0,0,1

In [9]:
fig = px.pie(recovered, values = 'Confirmed Count',names='Country/Region', height=600)
fig.update_traces(textposition='inside', textinfo='percent+label')

fig.update_layout(
    title_x = 0.5,
    geo=dict(
        showframe = False,
        showcoastlines = False,
    ))

fig.show()

ValueError: Value of 'values' is not the name of a column in 'data_frame'. Expected one of ['Province/State', 'Country/Region', '1/22/20', '1/23/20', '1/24/20', '1/25/20', '1/26/20', '1/27/20', '1/28/20', '1/29/20', '1/30/20', '1/31/20', '2/1/20', '2/2/20', '2/3/20', '2/4/20', '2/5/20', '2/6/20', '2/7/20', '2/8/20', '2/9/20', '2/10/20', '2/11/20', '2/12/20', '2/13/20', '2/14/20', '2/15/20', '2/16/20', '2/17/20', '2/18/20', '2/19/20', '2/20/20', '2/21/20', '2/22/20', '2/23/20', '2/24/20', '2/25/20', '2/26/20', '2/27/20', '2/28/20', '2/29/20', '3/1/20', '3/2/20', '3/3/20'] but received: Confirmed

In [15]:
rds_connection_string = "postgres:postgres@localhost:5432/corona_db"
engine = create_engine(f'postgresql://{rds_connection_string}')


df_combined.to_sql(name='corona_virus', con=engine, if_exists='append', index=False)

ModuleNotFoundError: No module named 'psycopg2'

In [1]:
pip install psycopg2

Collecting psycopg2
  Using cached https://files.pythonhosted.org/packages/84/d7/6a93c99b5ba4d4d22daa3928b983cec66df4536ca50b22ce5dcac65e4e71/psycopg2-2.8.4.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: running egg_info
    creating pip-egg-info/psycopg2.egg-info
    writing pip-egg-info/psycopg2.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'

    Error: pg_config executable not found.

    pg_config is required to build psycopg2 from source.  Please add the directory
    containing pg_config to the $PATH or specify the full executable path with the
    option:

        python setup.py build_ext --pg-config /path/to/pg_config build ...

    or with the pg_config option in 'setup.cfg'.

    If you prefer to avoid building psycopg2 from source, please install the PyPI
    'psycopg2-binary' package instead.

    For further information please check the 'doc/src/install.rst' file (also at
    <http://initd.org/psycopg/docs/install.html>).

    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/df/gpl1llk52pxfl4bvzcyj_gq80000gn/T/pip-install-2woa99wt/psycopg2/
Note: you may need to restart the kernel to use updated packages.