In [8]:
# Dependencies
import pandas as pd
import csv
from sqlalchemy import create_engine

In [9]:
#importing datasets
recovered = pd.read_csv('Resources/time_series_19-covid-Recovered.csv')
deaths = pd.read_csv('Resources/time_series_19-covid-Deaths.csv')
confirmed = pd.read_csv('Resources/time_series_19-covid-Confirmed.csv')

In [10]:
recovered.head()
recovered = recovered.drop(columns=['Lat', 'Long'])
df_recovered = pd.melt(recovered, id_vars=["Province/State", "Country/Region"])
df_recovered = df_recovered.rename(columns={"value": "Recovered Count", "variable": "Date"})
df_recovered.head()

  Province/State  Country/Region     Date  Recovered Count
0          Anhui  Mainland China  1/22/20                0
1        Beijing  Mainland China  1/22/20                0
2      Chongqing  Mainland China  1/22/20                0
3         Fujian  Mainland China  1/22/20                0
4          Gansu  Mainland China  1/22/20                0

In [11]:
deaths.head()
deaths = deaths.drop(columns=['Lat', 'Long'])
df_deaths = pd.melt(deaths, id_vars=["Province/State", "Country/Region"])
df_deaths = df_deaths.rename(columns={"value": "Deaths Count", "variable": "Date"})
df_deaths.head()

  Province/State  Country/Region     Date  Deaths Count
0          Anhui  Mainland China  1/22/20             0
1        Beijing  Mainland China  1/22/20             0
2      Chongqing  Mainland China  1/22/20             0
3         Fujian  Mainland China  1/22/20             0
4          Gansu  Mainland China  1/22/20             0

In [12]:
confirmed.head()
confirmed = confirmed.drop(columns=['Lat', 'Long'])
df_confirmed = pd.melt(confirmed, id_vars=["Province/State", "Country/Region"])
df_confirmed = df_confirmed.rename(columns={"value": "Confirmed Count", "variable": "Date"})
df_confirmed.head()

  Province/State  Country/Region     Date  Confirmed Count
0          Anhui  Mainland China  1/22/20                1
1        Beijing  Mainland China  1/22/20               14
2      Chongqing  Mainland China  1/22/20                6
3         Fujian  Mainland China  1/22/20                1
4          Gansu  Mainland China  1/22/20                0

In [13]:
df_combined = df_recovered.merge(df_deaths, on=("Province/State", "Country/Region", "Date"))
df_combined

,Province/State,Country/Region,Date,Recovered Count,Deaths Count
0,Anhui,Mainland China,1/22/20,0,0
1,Beijing,Mainland China,1/22/20,0,0
2,Chongqing,Mainland China,1/22/20,0,0
3,Fujian,Mainland China,1/22/20,0,0
4,Gansu,Mainland China,1/22/20,0,0
5,Guangdong,Mainland China,1/22/20,0,0
6,Guangxi,Mainland China,1/22/20,0,0
7,Guizhou,Mainland China,1/22/20,0,0
8,Hainan,Mainland China,1/22/20,0,0
9,Hebei,Mainland China,1/22/20,0,0
10,Heilongjiang,Mainland China,1/22/20,0,0
11,Henan,Mainland China,1/22/20,0,0
12,Hubei,Mainland China,1/22/20,28,17
13,Hunan,Mainland China,1/22/20,0,0
14,Inner Mongolia,Mainland China,1/22/20,0,0
15,Jiangsu,Mainland China,1/22/20,0,0
16,Jiangxi,Mainland China,1/22/20,0,0
17,Jilin,Mainland China,1/22/20,0,0
18,Liaoning,Mainland China,1/22/20,0,0
19,Ningxia,Mainland China,1/22/20,0,0
20,Qinghai,Mainland China,1/22/20,0,0
21,Shaanxi,Mainland China,1/22/20,0,0
22,Shandong,Mainland China,1/22/20,0,0
23,Shanghai,Mainland China,1/22/20,0,0
24,Shanxi,Mainland China,1/22/20,0,0
25,Sichuan,Mainland China,1/22/20,0,0
26,Tianjin,Mainland China,1/22/20,0,0
27,Tibet,Mainland China,1/22/20,0,0
28,Xinjiang,Mainland China,1/22/20,0,0
29,Yunnan,Mainland China,1/22/20,0,0
...,...,...,...,...,...
6312,NaN,Armenia,3/3/20,0,0
6313,NaN,Dominican Republic,3/3/20,0,0
6314,"Providence, RI",US,3/3/20,0,0
6315,NaN,Indonesia,3/3/20,0,0
6316,NaN,Portugal,3/3/20,0,0
6317,NaN,Andorra,3/3/20,0,0
6318,Tasmania,Australia,3/3/20,0,0
6319,NaN,Latvia,3/3/20,0,0
6320,NaN,Morocco,3/3/20,0,0
6321,NaN,Saudi Arabia,3/3/20,0,0
6322,NaN,Senegal,3/3/20,0,0
6323,"Grafton County, NH",US,3/3/20,0,0
6324,"Hillsborough, FL",US,3/3/20,0,0
6325,"New York City, NY",US,3/3/20,0,0
6326,"Placer County, CA",US,3/3/20,0,0
6327,"San Mateo, CA",US,3/3/20,0,0
6328,"Sarasota, FL",US,3/3/20,0,0
6329,"Sonoma County, CA",US,3/3/20,0,0
6330,"Umatilla, OR",US,3/3/20,0,0
6331,"Fulton County, GA",US,3/3/20,0,0
6332,"Washington County, OR",US,3/3/20,0,0
6333,NaN,Argentina,3/3/20,0,0
6334,NaN,Chile,3/3/20,0,0
6335,NaN,Jordan,3/3/20,0,0
6336,"Norfolk County, MA",US,3/3/20,0,0
6337,"Berkeley, CA",US,3/3/20,0,0
6338,"Maricopa County, AZ",US,3/3/20,0,0
6339,"Wake County, NC",US,3/3/20,0,0
6340,"Westchester County, NY",US,3/3/20,0,0
6341,NaN,Ukraine,3/3/20,0,0

In [14]:
df_combined = df_combined.merge(df_confirmed, on=("Province/State", "Country/Region", "Date"))
df_combined

,Province/State,Country/Region,Date,Recovered Count,Deaths Count,Confirmed Count
0,Anhui,Mainland China,1/22/20,0,0,1
1,Beijing,Mainland China,1/22/20,0,0,14
2,Chongqing,Mainland China,1/22/20,0,0,6
3,Fujian,Mainland China,1/22/20,0,0,1
4,Gansu,Mainland China,1/22/20,0,0,0
5,Guangdong,Mainland China,1/22/20,0,0,26
6,Guangxi,Mainland China,1/22/20,0,0,2
7,Guizhou,Mainland China,1/22/20,0,0,1
8,Hainan,Mainland China,1/22/20,0,0,4
9,Hebei,Mainland China,1/22/20,0,0,1
10,Heilongjiang,Mainland China,1/22/20,0,0,0
11,Henan,Mainland China,1/22/20,0,0,5
12,Hubei,Mainland China,1/22/20,28,17,444
13,Hunan,Mainland China,1/22/20,0,0,4
14,Inner Mongolia,Mainland China,1/22/20,0,0,0
15,Jiangsu,Mainland China,1/22/20,0,0,1
16,Jiangxi,Mainland China,1/22/20,0,0,2
17,Jilin,Mainland China,1/22/20,0,0,0
18,Liaoning,Mainland China,1/22/20,0,0,2
19,Ningxia,Mainland China,1/22/20,0,0,1
20,Qinghai,Mainland China,1/22/20,0,0,0
21,Shaanxi,Mainland China,1/22/20,0,0,0
22,Shandong,Mainland China,1/22/20,0,0,2
23,Shanghai,Mainland China,1/22/20,0,0,9
24,Shanxi,Mainland China,1/22/20,0,0,1
25,Sichuan,Mainland China,1/22/20,0,0,5
26,Tianjin,Mainland China,1/22/20,0,0,4
27,Tibet,Mainland China,1/22/20,0,0,0
28,Xinjiang,Mainland China,1/22/20,0,0,0
29,Yunnan,Mainland China,1/22/20,0,0,1
...,...,...,...,...,...,...
6312,NaN,Armenia,3/3/20,0,0,1
6313,NaN,Dominican Republic,3/3/20,0,0,1
6314,"Providence, RI",US,3/3/20,0,0,2
6315,NaN,Indonesia,3/3/20,0,0,2
6316,NaN,Portugal,3/3/20,0,0,2
6317,NaN,Andorra,3/3/20,0,0,1
6318,Tasmania,Australia,3/3/20,0,0,1
6319,NaN,Latvia,3/3/20,0,0,1
6320,NaN,Morocco,3/3/20,0,0,1
6321,NaN,Saudi Arabia,3/3/20,0,0,1
6322,NaN,Senegal,3/3/20,0,0,2
6323,"Grafton County, NH",US,3/3/20,0,0,2
6324,"Hillsborough, FL",US,3/3/20,0,0,2
6325,"New York City, NY",US,3/3/20,0,0,1
6326,"Placer County, CA",US,3/3/20,0,0,1
6327,"San Mateo, CA",US,3/3/20,0,0,2
6328,"Sarasota, FL",US,3/3/20,0,0,1
6329,"Sonoma County, CA",US,3/3/20,0,0,1
6330,"Umatilla, OR",US,3/3/20,0,0,1
6331,"Fulton County, GA",US,3/3/20,0,0,2
6332,"Washington County, OR",US,3/3/20,0,0,2
6333,NaN,Argentina,3/3/20,0,0,1
6334,NaN,Chile,3/3/20,0,0,1
6335,NaN,Jordan,3/3/20,0,0,1
6336,"Norfolk County, MA",US,3/3/20,0,0,1
6337,"Berkeley, CA",US,3/3/20,0,0,1
6338,"Maricopa County, AZ",US,3/3/20,0,0,1
6339,"Wake County, NC",US,3/3/20,0,0,1
6340,"Westchester County, NY",US,3/3/20,0,0,1
6341,NaN,Ukraine,3/3/20,0,0,1

In [15]:
rds_connection_string = "postgres:postgres@localhost:5432/corona_db"
engine = create_engine(f'postgresql://{rds_connection_string}')


df_combined.to_sql(name='corona_virus', con=engine, if_exists='append', index=False)

ModuleNotFoundError: No module named 'psycopg2'

In [1]:
pip install psycopg2

Collecting psycopg2
  Using cached https://files.pythonhosted.org/packages/84/d7/6a93c99b5ba4d4d22daa3928b983cec66df4536ca50b22ce5dcac65e4e71/psycopg2-2.8.4.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: running egg_info
    creating pip-egg-info/psycopg2.egg-info
    writing pip-egg-info/psycopg2.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'

    Error: pg_config executable not found.

    pg_config is required to build psycopg2 from source.  Please add the directory
    containing pg_config to the $PATH or specify the full executable path with the
    option:

        python setup.py build_ext --pg-config /path/to/pg_config build ...

    or with the pg_config option in 'setup.cfg'.

    If you prefer to avoid building psycopg2 from source, please install the PyPI
    'psycopg2-binary' package instead.

    For further information please check the 'doc/src/install.rst' file (also at
    <http://initd.org/psycopg/docs/install.html>).

    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/df/gpl1llk52pxfl4bvzcyj_gq80000gn/T/pip-install-2woa99wt/psycopg2/
Note: you may need to restart the kernel to use updated packages.